Added nginx conf to remove caching
Compete-McGill/wisp-ui pull request #62
Opened 2020-05-25 01:40 UTC by MohamedBeydoun

2020-05-25 01:43 UTC, ValerianClerc submitted a review, later dismissed
You know that I don't know anything about NGINX, so I'll just throw in this approval.

2020-05-25 01:48 UTC, idodin commented
I'm not sure I agree with this change - can we not update webpack configuration to hash files? That would allow users to cache but force retrieval of resources on new builds/releases

2020-05-26 20:03 UTC, ValerianClerc requested changes

2020-05-26 20:03 UTC, ValerianClerc commented on public/index.html
> +<html data-build-timestamp-utc="<%= new Date().toISOString() %>" lang="en">
Says “UTC” in the attribute name, but JavaScript’s Date object uses your local time zone. You should convert this to UTC.

2020-05-26 20:13 UTC, MohamedBeydoun commented on public/index.html
> +<html data-build-timestamp-utc="<%= new Date().toISOString() %>" lang="en">
ISO timestamps show time with an offset from UTC based on ur timezone. So after the conversion, the time will be in UTC.

2020-05-26 20:15 UTC, ValerianClerc commented on public/index.html
> +<html data-build-timestamp-utc="<%= new Date().toISOString() %>" lang="en">
Either remove “utc” from the attribute title, or explicitly convert to UTC in the JS imo

2020-05-26 20:28 UTC, ValerianClerc approved these changes

2020-05-26 21:03 UTC, imad-ant approved these changes
Lgtm!

2020-05-26 21:13 UTC, merged